## 네이버 검색 API 서비스

####  블로그

In [72]:
# 네이버 검색 API예제는 블로그를 비롯 전문자료까지 호출방법이 동일하므로 blog검색만 대표로 예제를 올렸습니다.
# 네이버 검색 Open API 예제 - 블로그 검색
import os
import sys
import urllib.request
client_id = "Jj0OXLwhiIThZiPeurcm"
client_secret = "Z34Uu4mSeJ"

query = urllib.parse.quote(input('검색어를 입력해주세요 : '))
url = "https://openapi.naver.com/v1/search/blog?query=" + query # json 결과
# url = "https://openapi.naver.com/v1/search/blog.xml?query=" + query # xml 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)

검색어를 입력해주세요 : 빅데이터
{
	"lastBuildDate":"Thu, 28 Jul 2022 17:12:49 +0900",
	"total":1144839,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"<b>빅데이터<\/b>전문가 준비를 위한 체계적인 방법",
			"link":"https:\/\/blog.naver.com\/nam8853nam?Redirect=Log&logNo=222802704648",
			"description":"그 중에서도 주목해 볼만한 분야가 바로 ‘<b>빅데이터<\/b>’ 라고 생각했어요. 기업이 이익을 창출하기... 이런 점들을 고려했을 때 1) 영업, 2) 컨설팅, 3) 제조 분야 모두 통틀어서 데이터 분석이 정말 중요한 부분을... ",
			"bloggername":"율맘 스토리",
			"bloggerlink":"https:\/\/blog.naver.com\/nam8853nam",
			"postdate":"20220707"
		},
		{
			"title":"<b>빅데이터<\/b>분석기사 실기 준비를 위한 학습루틴",
			"link":"https:\/\/blog.naver.com\/parkrapp?Redirect=Log&logNo=222753783578",
			"description":"안녕하세요, 오늘은 제가 도전한 <b>빅데이터<\/b>분석기사에 대한 정보를 많은 분과 나누고 싶어 이야기를... <b>빅데이터<\/b>를 이해하고 이를 분석, 수집, 저장 등의 시각화를 수행하는 실무자 역할을 하는 분석기사는... ",
			"bloggername":"황금빛 쭈롱월드",
			"bloggerlink":"https:\/\/blog.naver.com\/parkrapp",
			"postdate":"20220531"
		},
		{
			"title":"<b>빅데이터<\/b>전문가 공부했던 과정",
			"link":"https:\/\/blog.naver.com\/kmin4015?Redirect=Log&logNo=222802560555",
			"description":"<b>빅데이터<\/b>전문가 커리큘럼에서 다루고 있는 내용들은 1) 데이터 분석과 해석, 2) R 프로그램, 3) 요인 및 행렬, 4) 배열 및 리스트, 5) 패키지 등으로 구분해 볼 수 있는데요. 필요한 내용은 알차게 모두 구성되어 있는... ",
			"bloggername":"나날",
			"bloggerlink":"https:\/\/blog.naver.com\/kmin4015",
			"postdate":"20220707"
		},
		{
			"title":"<b>빅데이터<\/b>전문가 꼼꼼한 학습 노하우",
			"link":"https:\/\/blog.naver.com\/dbsrptkdgod?Redirect=Log&logNo=222803100328",
			"description":"<b>빅데이터<\/b>전문가 강의에서 다루고 있는 내용들은 1) 해석과 분석, 2) 프로그램 실행, 3) 데이터의 구분 및 유형, 4) 요인 및 행렬, 5) 패키지 등이 있었는데요. 전체적인 내용을 듣고 숙지한 다음에, 개념적인 부분은... ",
			"bloggername":"나",
			"bloggerlink":"https:\/\/blog.naver.com\/dbsrptkdgod",
			"postdate":"20220707"
		},
		{
			"title":"<b>빅데이터<\/b>전문가 대비하는 핵심 노하우",
			"link":"https:\/\/blog.naver.com\/zkfk1116?Redirect=Log&logNo=222803090088",
			"description":"과정에서 다루고 있는 내용들은 1) <b>빅데이터<\/b>란?, 2) R 프로그램, 3) 벡터, 4) 데이터 등으로 나누어볼 수 있는데요. 생각했던 것 보다 적은 강의 수 였지만 필요한 내용이 알차게 구성되어 있는 조건이라서 커리큘럼... ",
			"bloggername":"실버푸들아미",
			"bloggerlink":"https:\/\/blog.naver.com\/zkfk1116",
			"postdate":"20220707"
		},
		{
			"title":"<b>빅데이터<\/b>학원 이젠 AWS클라우드까지 체계적으로!",
			"link":"https:\/\/blog.naver.com\/jeongok8602?Redirect=Log&logNo=222706245644",
			"description":"그만큼 계절의 변화가 뚜렷하게 나타나고 있는 지금은 <b>빅데이터<\/b> 관련 분야로 취업을 하고 1년차로... 부분은 데이터베이스의 분석이라고 할 수 있는데 여기서 배우는 프로그램이 파이썬을 배우고 프론트엔드에... ",
			"bloggername":"호박공주맘의 시시콜콜",
			"bloggerlink":"https:\/\/blog.naver.com\/jeongok8602",
			"postdate":"20220420"
		},
		{
			"title":"<b>빅데이터<\/b> 자격증 준비 노하우와 활용 과정",
			"link":"https:\/\/blog.naver.com\/sweety4338?Redirect=Log&logNo=222782751481",
			"description":"정의, <b>빅 데이터<\/b> 필요성, 구성과 범위, 데이터 활용의 의미, R 프로그래밍 기본과 같이 <b>빅데이터<\/b>자격증 학습할 때 기본적인 것들을 배우기 시작합니다 처음에는 따라가기 어렵기도 했지만, 소수 정예 수업에 한... ",
			"bloggername":"MY 지식@",
			"bloggerlink":"https:\/\/blog.naver.com\/sweety4338",
			"postdate":"20220621"
		},
		{
			"title":"<b>빅데이터<\/b>자격증 활용 방법 및 공부 팁",
			"link":"https:\/\/blog.naver.com\/hjjkr?Redirect=Log&logNo=222803875339",
			"description":"마케팅 업무를 하는 분들이라면 <b>빅데이터<\/b>의 중요성에 대해서 공감하실 수 있을 것 같아요. 실제 관련... 산적해 있는 각종 데이터들을 수집, 분석 및 통계를 내어 이를 가지고 기업의 이익이 될 수 있도록 도움을... ",
			"bloggername":"원주불곰댁 꼼지락 하우스",
			"bloggerlink":"https:\/\/blog.naver.com\/hjjkr",
			"postdate":"20220708"
		},
		{
			"title":"<b>빅데이터<\/b> 교육 단계별 맞춤형 학습과정",
			"link":"https:\/\/blog.naver.com\/dorothy2648?Redirect=Log&logNo=222756586083",
			"description":"통해 <b>빅데이터<\/b> 교육에 대해 알게 되었습니다 이러한 이류로 여러 가지 기술에 대해서 알아보았고, 그 중에서도 가장 관심 있고 예전부터 취득하고 싶었던 <b>빅데이터<\/b> 분석기사를 따 보려고 계획을 세웠습니다... ",
			"bloggername":"오즈미니",
			"bloggerlink":"https:\/\/blog.naver.com\/dorothy2648",
			"postdate":"20220602"
		},
		{
			"title":"<b>빅데이터<\/b>자격증 취득을 목표로 한 분석방법",
			"link":"https:\/\/blog.naver.com\/gywls5012?Redirect=Log&logNo=222808899184",
			"description":"필요한 데이터만 모아서 사람들이 원하는 것을 뽑아낼 수 있는 능력을 가지고 싶었죠. 제가 앞으로 사회에 나가서 취직을 하는 것에 큰 도움을 받을 수 있을 것 같아서 합격률이 40% 정도인 <b>빅데이터<\/b> 시험 취득... ",
			"bloggername":"원두커피전국최저가판매\/세보커피머신수리as전문",
			"bloggerlink":"https:\/\/blog.naver.com\/gywls5012",
			"postdate":"20220712"
		}
	]
}

In [73]:
from bs4 import BeautifulSoup
import warnings
warnings.filterwarnings('ignore')

xml = response_body.decode('utf-8') # 위에서 바디를 불러왔었음
bs = BeautifulSoup(xml, 'lxml')
bs.get_text()

'{\n\t"lastBuildDate":"Thu, 28 Jul 2022 17:12:49 +0900",\n\t"total":1144839,\n\t"start":1,\n\t"display":10,\n\t"items":[\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>전문가 준비를 위한 체계적인 방법",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/nam8853nam?Redirect=Log&logNo=222802704648",\n\t\t\t"description":"그 중에서도 주목해 볼만한 분야가 바로 ‘빅데이터<\\/b>’ 라고 생각했어요. 기업이 이익을 창출하기... 이런 점들을 고려했을 때 1) 영업, 2) 컨설팅, 3) 제조 분야 모두 통틀어서 데이터 분석이 정말 중요한 부분을... ",\n\t\t\t"bloggername":"율맘 스토리",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/nam8853nam",\n\t\t\t"postdate":"20220707"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>분석기사 실기 준비를 위한 학습루틴",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/parkrapp?Redirect=Log&logNo=222753783578",\n\t\t\t"description":"안녕하세요, 오늘은 제가 도전한 빅데이터<\\/b>분석기사에 대한 정보를 많은 분과 나누고 싶어 이야기를... 빅데이터<\\/b>를 이해하고 이를 분석, 수집, 저장 등의 시각화를 수행하는 실무자 역할을 하는 분석기사는... ",\n\t\t\t"bloggername":"황금빛 쭈롱월드",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/parkrapp",\n\t\t\t"postdate":"20220531"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>전문가 공부했던 과정",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/kmin4015?Redirect=Log&logNo=222802560555",\n\t\t\t"description":"빅데이터<\\/b>전문가 커리큘럼에서 다루고 있는 내용들은 1) 데이터 분석과 해석, 2) R 프로그램, 3) 요인 및 행렬, 4) 배열 및 리스트, 5) 패키지 등으로 구분해 볼 수 있는데요. 필요한 내용은 알차게 모두 구성되어 있는... ",\n\t\t\t"bloggername":"나날",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/kmin4015",\n\t\t\t"postdate":"20220707"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>전문가 꼼꼼한 학습 노하우",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/dbsrptkdgod?Redirect=Log&logNo=222803100328",\n\t\t\t"description":"빅데이터<\\/b>전문가 강의에서 다루고 있는 내용들은 1) 해석과 분석, 2) 프로그램 실행, 3) 데이터의 구분 및 유형, 4) 요인 및 행렬, 5) 패키지 등이 있었는데요. 전체적인 내용을 듣고 숙지한 다음에, 개념적인 부분은... ",\n\t\t\t"bloggername":"나",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/dbsrptkdgod",\n\t\t\t"postdate":"20220707"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>전문가 대비하는 핵심 노하우",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/zkfk1116?Redirect=Log&logNo=222803090088",\n\t\t\t"description":"과정에서 다루고 있는 내용들은 1) 빅데이터<\\/b>란?, 2) R 프로그램, 3) 벡터, 4) 데이터 등으로 나누어볼 수 있는데요. 생각했던 것 보다 적은 강의 수 였지만 필요한 내용이 알차게 구성되어 있는 조건이라서 커리큘럼... ",\n\t\t\t"bloggername":"실버푸들아미",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/zkfk1116",\n\t\t\t"postdate":"20220707"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>학원 이젠 AWS클라우드까지 체계적으로!",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/jeongok8602?Redirect=Log&logNo=222706245644",\n\t\t\t"description":"그만큼 계절의 변화가 뚜렷하게 나타나고 있는 지금은 빅데이터<\\/b> 관련 분야로 취업을 하고 1년차로... 부분은 데이터베이스의 분석이라고 할 수 있는데 여기서 배우는 프로그램이 파이썬을 배우고 프론트엔드에... ",\n\t\t\t"bloggername":"호박공주맘의 시시콜콜",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/jeongok8602",\n\t\t\t"postdate":"20220420"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b> 자격증 준비 노하우와 활용 과정",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/sweety4338?Redirect=Log&logNo=222782751481",\n\t\t\t"description":"정의, 빅 데이터<\\/b> 필요성, 구성과 범위, 데이터 활용의 의미, R 프로그래밍 기본과 같이 빅데이터<\\/b>자격증 학습할 때 기본적인 것들을 배우기 시작합니다 처음에는 따라가기 어렵기도 했지만, 소수 정예 수업에 한... ",\n\t\t\t"bloggername":"MY 지식@",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/sweety4338",\n\t\t\t"postdate":"20220621"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>자격증 활용 방법 및 공부 팁",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/hjjkr?Redirect=Log&logNo=222803875339",\n\t\t\t"description":"마케팅 업무를 하는 분들이라면 빅데이터<\\/b>의 중요성에 대해서 공감하실 수 있을 것 같아요. 실제 관련... 산적해 있는 각종 데이터들을 수집, 분석 및 통계를 내어 이를 가지고 기업의 이익이 될 수 있도록 도움을... ",\n\t\t\t"bloggername":"원주불곰댁 꼼지락 하우스",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/hjjkr",\n\t\t\t"postdate":"20220708"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b> 교육 단계별 맞춤형 학습과정",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/dorothy2648?Redirect=Log&logNo=222756586083",\n\t\t\t"description":"통해 빅데이터<\\/b> 교육에 대해 알게 되었습니다 이러한 이류로 여러 가지 기술에 대해서 알아보았고, 그 중에서도 가장 관심 있고 예전부터 취득하고 싶었던 빅데이터<\\/b> 분석기사를 따 보려고 계획을 세웠습니다... ",\n\t\t\t"bloggername":"오즈미니",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/dorothy2648",\n\t\t\t"postdate":"20220602"\n\t\t},\n\t\t{\n\t\t\t"title":"빅데이터<\\/b>자격증 취득을 목표로 한 분석방법",\n\t\t\t"link":"https:\\/\\/blog.naver.com\\/gywls5012?Redirect=Log&logNo=222808899184",\n\t\t\t"description":"필요한 데이터만 모아서 사람들이 원하는 것을 뽑아낼 수 있는 능력을 가지고 싶었죠. 제가 앞으로 사회에 나가서 취직을 하는 것에 큰 도움을 받을 수 있을 것 같아서 합격률이 40% 정도인 빅데이터<\\/b> 시험 취득... ",\n\t\t\t"bloggername":"원두커피전국최저가판매\\/세보커피머신수리as전문",\n\t\t\t"bloggerlink":"https:\\/\\/blog.naver.com\\/gywls5012",\n\t\t\t"postdate":"20220712"\n\t\t}\n\t]\n}'

#### Q. 네이버 웹문서에서 빅데이터에 대한 데이터를 가져와서 데이터프레임으로 출력하세요.(api 가이드 참조)

In [113]:
import urllib.request
import requests
from bs4 import BeautifulSoup
url = 'https://openapi.naver.com/v1/search/webkr.xml?query='+urllib.parse.quote(input('검색어 : '))
# url = "https://openapi.naver.com/v1/search/blog?query="
client_id = "Jj0OXLwhiIThZiPeurcm"
client_secret = "Z34Uu4mSeJ"

response = requests.get(url)
# bs = BeautifulSoup(response, 'html.parser')
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    a = response_body.decode('utf-8')
    print(a)
else:
    print("Error Code:" + rescode)

import warnings
warnings.filterwarnings('ignore')
import pandas as pd
# df = pd.read_json(response_body.decode('utf-8'))
# df

검색어 : 빅데이터
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Naver Open API - webkr ::&apos;빅데이터&apos;</title><link>https://search.naver.com</link><description>Naver Search Result</description><lastBuildDate>Thu, 28 Jul 2022 18:46:47 +0900</lastBuildDate><total>38497617</total><start>1</start><display>10</display><item><title>&lt;b&gt;빅 데이터&lt;/b&gt; 프로세싱 - 나무위키</title><link>https://namu.wiki/w/%EB%B9%85%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%94%84%EB%A1%9C%EC%84%B8%EC%8B%B1</link><description>Big data processing 디지털 시대에서 폭증하는 &apos;방대한 양의 &lt;b&gt;데이터&lt;/b&gt;(big data)&apos;를 관리하고 분석해서 유용한 정보로 사용하는 기술.</description></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;란? | 고급 &lt;b&gt;빅데이터&lt;/b&gt; 분석 | SAP Insights</title><link>https://www.sap.com/korea/insights/what-is-big-data.html</link><description>비즈니스에 대한 360도 통찰을 제공하고 디지털 노이즈 속에 숨은 성장 기회를 찾도록 돕는 &lt;b&gt;빅데이터&lt;/b&gt; 솔루션을 만나보세요.</description></item><item><title>&lt;b&gt;빅 데이터&lt;/b&gt;란 무엇입니까? | Oracle 대한민국</title><link>https://www.oracle.com/kr/big-data/what-is-big-data/</link><description>&lt;b&gt;빅데이터&lt;/b&gt;는 특히 새로운 &lt;b&gt;데이터&lt;/b&gt; 소스에서 나온 더 크고 더 복잡한 &lt;b&gt;데이터&lt;/b&gt; 세트입니다. &lt;b&gt;빅데이터&lt;/b&gt;의 이점, 과제 및 모범 사례 외에도 정의 및 역사에 대해 알아보세요.</description></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;(big data) 이해 - 정의, 분석, 기술, 특징, 사례 연구</title><link>https://www.redhat.com/ko/topics/big-data</link><description>&lt;b&gt;빅데이터&lt;/b&gt;(big data)란 기존 &lt;b&gt;데이터&lt;/b&gt; 프로세싱 방식을 넘어선 대규모의 정형/비정형의 복잡한 &lt;b&gt;데이터&lt;/b&gt;에 대한 분석 기술입니다. &lt;b&gt;빅 데이터&lt;/b&gt;의 정의, 특징, 사례를 설명합니다.</description></item><item><title>네이버 &lt;b&gt;데이터&lt;/b&gt;랩</title><link>https://datalab.naver.com/</link><description>네이버의 검색 트렌드 및 급상승검색어 이력, 쇼핑 카테고리별 검색 트렌드 제공</description></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt; - BC카드</title><link>https://www.bccard.com/card/html/company/kr/bigdata/business/index.jsp</link><description>fnbigdata.com &lt;b&gt;빅데이터&lt;/b&gt; 생태계 조성 기반 마련, &lt;b&gt;빅데이터&lt;/b&gt; 수요자의 &lt;b&gt;데이터&lt;/b&gt; 분석, &lt;b&gt;데이터&lt;/b&gt; 협력 네트워킹 통합 지원 공안 운영시간 : 평일 오전 9시 ~ 오후 6시 위치 : 을지로 3가역 대신파이낸스빌딩 WeWork 16층 112호</description></item><item><title>트라이빅 소개 &amp;lt; 서비스 안내 : KOTRA 무역투자&lt;b&gt;빅데이터&lt;/b&gt; - 코트라 무역투자 24</title><link>https://www.kotra.or.kr/bigdata/guide</link><description>&apos;+getMessage(&apos;button.close&apos;)+&apos;국가정보, 시장정보, 해외시장뉴스, 수입규제 정보 등 품목(HS CODE) 기준 글로벌 교역 및 투자 통계 &lt;b&gt;데이터&lt;/b&gt; 시장별 호/부진 품목 및 통계 정보 등 해외기업 DB 기반 기업별... </description></item><item><title>국가기술 &lt;b&gt;빅데이터&lt;/b&gt; 분석기사 - &lt;b&gt;데이터&lt;/b&gt;자격시험</title><link>https://www.dataq.or.kr/www/sub/a_07.do</link><description>정형, 반정형, 비정형 등 다양한 형태의 &lt;b&gt;데이터&lt;/b&gt;를 읽을 수 있다. 필요시 공개 &lt;b&gt;데이터&lt;/b&gt;를 수집할 수 있다.... &lt;b&gt;데이터&lt;/b&gt;의 유형을 원하는 형태로 변환할 수 있다. &lt;b&gt;데이터&lt;/b&gt;의 범위를 표준화 또는 정규화를 통해 일치시킬 수... </description></item><item><title>&lt;b&gt;빅데이터&lt;/b&gt;의 이해 - 글이 작품이 되는 공간, 브런치</title><link>https://brunch.co.kr/@linecard/319</link><description>&lt;b&gt;빅데이터&lt;/b&gt;의 등장 디지털 경제가 확산되면서 아날로그 경제와는 비교가 되지 않을 정도로 많은 정보와 &lt;b&gt;데이터&lt;/b&gt;가 생산됩니다. 매 분마다 엄청난 양의 &lt;b&gt;데이터&lt;/b&gt;가 쏟아지고 있습니다. 매 1 분 동안 구글은 200만 건의 검색 결과, 유튜브는 72시간 분량의 비디오, 스카이프는 140만 건의 연결, 메일은 2억 4백만 개가 전송됩니다. 인터넷에 방대한 규모의 문자, 이미</description></item><item><title>미디어백과: &lt;b&gt;빅데이터&lt;/b&gt; - 네이버 지식백과</title><link>https://terms.naver.com/list.nhn?cid=42183&amp;categoryId=42183</link><description>미디어백과: &lt;b&gt;빅데이터&lt;/b&gt;에 관한 정보 제공</description></item></channel></rss>

In [110]:
import pandas as pd
df.loc[ind] = [title,link]

df = pd.DataFrame(columns=['title','link'])
df


bs = BeautifulSoup(response, 'html.parser')
bs2.find('div', id = 'dic_area').text

NameError: name 'title' is not defined

- 과제 07/28 (1)

웹문서에서 빅데이터에 대한 의미있는 정보로 구성된 데이터프레임을 출력하세요.
(title, link, description)

In [2]:
import os
import sys
import urllib.request
client_id = "Jj0OXLwhiIThZiPeurcm"
client_secret = "Z34Uu4mSeJ"

query = urllib.parse.quote("빅데이터")
url = 'https://openapi.naver.com/v1/search/webkr.json?query='+query # json 결과
# url = "https://openapi.naver.com/v1/search/webkr.json?query=" + encText # xml 결과
request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
df = pd.read_json(response_body.decode('utf-8'))
df

{
	"lastBuildDate":"Fri, 29 Jul 2022 08:50:12 +0900",
	"total":38809053,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"<b>빅 데이터<\/b> 프로세싱 - 나무위키",
			"link":"https:\/\/namu.wiki\/w\/%EB%B9%85%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%ED%94%84%EB%A1%9C%EC%84%B8%EC%8B%B1",
			"description":"Big data processing 디지털 시대에서 폭증하는 '방대한 양의 <b>데이터<\/b>(big data)'를 관리하고 분석해서 유용한 정보로 사용하는 기술."
		},
		{
			"title":"<b>빅데이터<\/b>란? | 고급 <b>빅데이터<\/b> 분석 | SAP Insights",
			"link":"https:\/\/www.sap.com\/korea\/insights\/what-is-big-data.html",
			"description":"비즈니스에 대한 360도 통찰을 제공하고 디지털 노이즈 속에 숨은 성장 기회를 찾도록 돕는 <b>빅데이터<\/b> 솔루션을 만나보세요."
		},
		{
			"title":"<b>빅 데이터<\/b>란 무엇입니까? | Oracle 대한민국",
			"link":"https:\/\/www.oracle.com\/kr\/big-data\/what-is-big-data\/",
			"description":"<b>빅데이터<\/b>는 특히 새로운 <b>데이터<\/b> 소스에서 나온 더 크고 더 복잡한 <b>데이터<\/b> 세트입니다. <b>빅데이터<\/b>의 이점, 과제 및 모범 사례 외에도 정의 및 역사에 대해 알아보세요."
		},
		{
			"title":"<b>빅데이터<\/b>(big data) 이해 - 정의, 분석, 기술, 특징, 사례 연구",
			"link":"https:\/\/www.redhat.com\/ko\/topics\/big-data",
			"description":"<b>빅데이터<\/b>(big data)란 기존 <b>데이터<\/b> 프로세싱 방식을 넘어선 대규모의 정형\/비정형의 복잡한 <b>데이터<\/b>에 대한 분석 기술입니다. <b>빅 데이터<\/b>의 정의, 특징, 사례를 설명합니다."
		},
		{
			"title":"네이버 <b>데이터<\/b>랩",
			"link":"https:\/\/datalab.naver.com\/",
			"description":"네이버의 검색 트렌드 및 급상승검색어 이력, 쇼핑 카테고리별 검색 트렌드 제공"
		},
		{
			"title":"<b>빅데이터<\/b> - BC카드",
			"link":"https:\/\/www.bccard.com\/card\/html\/company\/kr\/bigdata\/business\/index.jsp",
			"description":"fnbigdata.com <b>빅데이터<\/b> 생태계 조성 기반 마련, <b>빅데이터<\/b> 수요자의 <b>데이터<\/b> 분석, <b>데이터<\/b> 협력 네트워킹 통합 지원 공안 운영시간 : 평일 오전 9시 ~ 오후 6시 위치 : 을지로 3가역 대신파이낸스빌딩 WeWork 16층 112호"
		},
		{
			"title":"트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자<b>빅데이터<\/b> - 코트라 무역투자 24",
			"link":"https:\/\/www.kotra.or.kr\/bigdata\/guide",
			"description":"'+getMessage('button.close')+'국가정보, 시장정보, 해외시장뉴스, 수입규제 정보 등 품목(HS CODE) 기준 글로벌 교역 및 투자 통계 <b>데이터<\/b> 시장별 호\/부진 품목 및 통계 정보 등 해외기업 DB 기반 기업별... "
		},
		{
			"title":"국가기술 <b>빅데이터<\/b> 분석기사 - <b>데이터<\/b>자격시험",
			"link":"https:\/\/www.dataq.or.kr\/www\/sub\/a_07.do",
			"description":"정형, 반정형, 비정형 등 다양한 형태의 <b>데이터<\/b>를 읽을 수 있다. 필요시 공개 <b>데이터<\/b>를 수집할 수 있다.... <b>데이터<\/b>의 유형을 원하는 형태로 변환할 수 있다. <b>데이터<\/b>의 범위를 표준화 또는 정규화를 통해 일치시킬 수... "
		},
		{
			"title":"<b>빅데이터<\/b>의 이해 - 글이 작품이 되는 공간, 브런치",
			"link":"https:\/\/brunch.co.kr\/@linecard\/319",
			"description":"<b>빅데이터<\/b>의 등장 디지털 경제가 확산되면서 아날로그 경제와는 비교가 되지 않을 정도로 많은 정보와 <b>데이터<\/b>가 생산됩니다. 매 분마다 엄청난 양의 <b>데이터<\/b>가 쏟아지고 있습니다. 매 1 분 동안 구글은 200만 건의 검색 결과, 유튜브는 72시간 분량의 비디오, 스카이프는 140만 건의 연결, 메일은 2억 4백만 개가 전송됩니다. 인터넷에 방대한 규모의 문자, 이미"
		},
		{
			"title":"미디어백과: <b>빅데이터<\/b> - 네이버 지식백과",
			"link":"https:\/\/terms.naver.com\/list.nhn?cid=42183&categoryId=42183",
			"description":"미디어백과: <b>빅데이터<\/b>에 관한 정보 제공"
		}
	]
}

,lastBuildDate,total,start,display,items
0,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,"{'title': '<b>빅 데이터</b> 프로세싱 - 나무위키', 'link': ..."
1,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,{'title': '<b>빅데이터</b>란? | 고급 <b>빅데이터</b> 분석 |...
2,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,{'title': '<b>빅 데이터</b>란 무엇입니까? | Oracle 대한민국'...
3,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,"{'title': '<b>빅데이터</b>(big data) 이해 - 정의, 분석, ..."
4,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,"{'title': '네이버 <b>데이터</b>랩', 'link': 'https://..."
5,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,"{'title': '<b>빅데이터</b> - BC카드', 'link': 'https..."
6,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,{'title': '트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자<b>...
7,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,{'title': '국가기술 <b>빅데이터</b> 분석기사 - <b>데이터</b>자...
8,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,"{'title': '<b>빅데이터</b>의 이해 - 글이 작품이 되는 공간, 브런치..."
9,"Fri, 29 Jul 2022 08:50:12 +0900",38809053,1,10,"{'title': '미디어백과: <b>빅데이터</b> - 네이버 지식백과', 'li..."

In [3]:
df['items'][0]['title']
df['items'][0]['link']
df['items'][0]['description']

"Big data processing 디지털 시대에서 폭증하는 '방대한 양의 <b>데이터</b>(big data)'를 관리하고 분석해서 유용한 정보로 사용하는 기술."

In [4]:
df['items']

0    {'title': '<b>빅 데이터</b> 프로세싱 - 나무위키', 'link': ...
1    {'title': '<b>빅데이터</b>란? | 고급 <b>빅데이터</b> 분석 |...
2    {'title': '<b>빅 데이터</b>란 무엇입니까? | Oracle 대한민국'...
3    {'title': '<b>빅데이터</b>(big data) 이해 - 정의, 분석, ...
4    {'title': '네이버 <b>데이터</b>랩', 'link': 'https://...
5    {'title': '<b>빅데이터</b> - BC카드', 'link': 'https...
6    {'title': '트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자<b>...
7    {'title': '국가기술 <b>빅데이터</b> 분석기사 - <b>데이터</b>자...
8    {'title': '<b>빅데이터</b>의 이해 - 글이 작품이 되는 공간, 브런치...
9    {'title': '미디어백과: <b>빅데이터</b> - 네이버 지식백과', 'li...
Name: items, dtype: object

In [6]:
import json
import re
dic_data = json.loads(response_body.decode('utf-8'))
a = dic_data['items']

df1 = pd.DataFrame(a)
df1

,title,link,description
0,<b>빅 데이터</b> 프로세싱 - 나무위키,https://namu.wiki/w/%EB%B9%85%20%EB%8D%B0%EC%9...,Big data processing 디지털 시대에서 폭증하는 '방대한 양의 <b>데...
1,<b>빅데이터</b>란? | 고급 <b>빅데이터</b> 분석 | SAP Insights,https://www.sap.com/korea/insights/what-is-big...,비즈니스에 대한 360도 통찰을 제공하고 디지털 노이즈 속에 숨은 성장 기회를 찾도...
2,<b>빅 데이터</b>란 무엇입니까? | Oracle 대한민국,https://www.oracle.com/kr/big-data/what-is-big...,<b>빅데이터</b>는 특히 새로운 <b>데이터</b> 소스에서 나온 더 크고 더 ...
3,"<b>빅데이터</b>(big data) 이해 - 정의, 분석, 기술, 특징, 사례 연구",https://www.redhat.com/ko/topics/big-data,<b>빅데이터</b>(big data)란 기존 <b>데이터</b> 프로세싱 방식을 ...
4,네이버 <b>데이터</b>랩,https://datalab.naver.com/,"네이버의 검색 트렌드 및 급상승검색어 이력, 쇼핑 카테고리별 검색 트렌드 제공"
5,<b>빅데이터</b> - BC카드,https://www.bccard.com/card/html/company/kr/bi...,"fnbigdata.com <b>빅데이터</b> 생태계 조성 기반 마련, <b>빅데이..."
6,트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자<b>빅데이터</b> - ...,https://www.kotra.or.kr/bigdata/guide,"'+getMessage('button.close')+'국가정보, 시장정보, 해외시장..."
7,국가기술 <b>빅데이터</b> 분석기사 - <b>데이터</b>자격시험,https://www.dataq.or.kr/www/sub/a_07.do,"정형, 반정형, 비정형 등 다양한 형태의 <b>데이터</b>를 읽을 수 있다. 필요..."
8,"<b>빅데이터</b>의 이해 - 글이 작품이 되는 공간, 브런치",https://brunch.co.kr/@linecard/319,<b>빅데이터</b>의 등장 디지털 경제가 확산되면서 아날로그 경제와는 비교가 되지...
9,미디어백과: <b>빅데이터</b> - 네이버 지식백과,https://terms.naver.com/list.nhn?cid=42183&cat...,미디어백과: <b>빅데이터</b>에 관한 정보 제공

In [203]:
df2 = df.drop('items', axis=1) # 처음 뽑은 df표 items 열 삭제
df2

                     lastBuildDate     total  start  display
0  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
1  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
2  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
3  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
4  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
5  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
6  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
7  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
8  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10
9  Thu, 28 Jul 2022 20:18:25 +0900  38520891      1       10

In [205]:
df3 = df2.join(df1)
df3 # items 열 삭제후 안에서 뽑은 정보들 붙여줌

,lastBuildDate,total,start,display,title,link,description
0,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,<b>빅 데이터</b> 프로세싱 - 나무위키,https://namu.wiki/w/%EB%B9%85%20%EB%8D%B0%EC%9...,Big data processing 디지털 시대에서 폭증하는 '방대한 양의 <b>데...
1,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,<b>빅데이터</b>란? | 고급 <b>빅데이터</b> 분석 | SAP Insights,https://www.sap.com/korea/insights/what-is-big...,비즈니스에 대한 360도 통찰을 제공하고 디지털 노이즈 속에 숨은 성장 기회를 찾도...
2,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,<b>빅 데이터</b>란 무엇입니까? | Oracle 대한민국,https://www.oracle.com/kr/big-data/what-is-big...,<b>빅데이터</b>는 특히 새로운 <b>데이터</b> 소스에서 나온 더 크고 더 ...
3,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,"<b>빅데이터</b>(big data) 이해 - 정의, 분석, 기술, 특징, 사례 연구",https://www.redhat.com/ko/topics/big-data,<b>빅데이터</b>(big data)란 기존 <b>데이터</b> 프로세싱 방식을 ...
4,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,네이버 <b>데이터</b>랩,https://datalab.naver.com/,"네이버의 검색 트렌드 및 급상승검색어 이력, 쇼핑 카테고리별 검색 트렌드 제공"
5,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,<b>빅데이터</b> - BC카드,https://www.bccard.com/card/html/company/kr/bi...,"fnbigdata.com <b>빅데이터</b> 생태계 조성 기반 마련, <b>빅데이..."
6,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,트라이빅 소개 &lt; 서비스 안내 : KOTRA 무역투자<b>빅데이터</b> - ...,https://www.kotra.or.kr/bigdata/guide,"'+getMessage('button.close')+'국가정보, 시장정보, 해외시장..."
7,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,국가기술 <b>빅데이터</b> 분석기사 - <b>데이터</b>자격시험,https://www.dataq.or.kr/www/sub/a_07.do,"정형, 반정형, 비정형 등 다양한 형태의 <b>데이터</b>를 읽을 수 있다. 필요..."
8,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,"<b>빅데이터</b>의 이해 - 글이 작품이 되는 공간, 브런치",https://brunch.co.kr/@linecard/319,<b>빅데이터</b>의 등장 디지털 경제가 확산되면서 아날로그 경제와는 비교가 되지...
9,"Thu, 28 Jul 2022 20:18:25 +0900",38520891,1,10,미디어백과: <b>빅데이터</b> - 네이버 지식백과,https://terms.naver.com/list.nhn?cid=42183&cat...,미디어백과: <b>빅데이터</b>에 관한 정보 제공

- 과제 07/28 (2)

뉴스, 영화, 쇼핑, 지식in, 카페글에서 적합한 주제에 대한 데이터를 가져와 데이터프레임으로 출력하세요.

In [10]:
import os
import sys
import urllib.request
import warnings
warnings.filterwarnings('ignore')


client_id = "Jj0OXLwhiIThZiPeurcm"
client_secret = "Z34Uu4mSeJ"

query = urllib.parse.quote(input("검색"))
url = 'https://openapi.naver.com/v1/search/kin.json?query='+ query   # 지식인 주소, json형식
# url = f"https://openapi.naver.com/v1/search/webkr.xml?query={query}&display=10&start=1"

request = urllib.request.Request(url)
request.add_header("X-Naver-Client-Id",client_id)
request.add_header("X-Naver-Client-Secret",client_secret)
response = urllib.request.urlopen(request)
rescode = response.getcode()
if(rescode==200):
    response_body = response.read()
    print(response_body.decode('utf-8'))
else:
    print("Error Code:" + rescode)
    
import pandas as pd
df = pd.read_json(response_body.decode('utf-8'))
df

검색빅데이터 분석기사
{
	"lastBuildDate":"Fri, 29 Jul 2022 09:23:22 +0900",
	"total":15236,
	"start":1,
	"display":10,
	"items":[
		{
			"title":"<b>빅데이터 분석기사<\/b>",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=4&dirId=40608&docId=420897183&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=1&search_sort=0&spq=0",
			"description":"<b>빅데이터 분석기사<\/b>가 되기 위해서는 아무나 될 수가 없다고 들었습니다 되기 위해서 어떤 조건을 충족해야 하나요? 무슨 전공 무슨 경력 등등을 쌓아야 한다고 들어서요! 알려주세요!  안녕하세요 질문자님! 질문자님의 답변에 수기로... "
		},
		{
			"title":"<b>빅데이터 분석기사<\/b> 전공관련",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=111&docId=401859262&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=2&search_sort=0&spq=0",
			"description":"... 아무리 찾아봐도 정보가 없어서요. <b>빅데이터분석기사<\/b>는 전공, 비전공 제한이 없어요. 모든 학과가 응시가 가능한 기사 자격증입니다. 따라서 4년제 사진학과 졸업하셨으면 무조건 <b>빅데이터분석기사<\/b>에 응시할 수 있습니다. "
		},
		{
			"title":"<b>빅데이터분석기사<\/b> 해볼까요?",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=101&docId=414209192&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=3&search_sort=0&spq=0",
			"description":"<b>빅데이터분석기사<\/b> 해볼지 고심중인데요. 제가 <b>빅데이터분석기사<\/b>에 흥미를 느끼게 되어서 진지하게 <b>빅데이터분석기사<\/b> 배워보고 싶어요. 제가 좀 알아보기는 했는데 <b>빅데이터분석기사<\/b> 관해서 많은것을 알아보기 좀 힘들더라고요. 그래서... "
		},
		{
			"title":"정보처리기사 vs <b>빅데이터분석기사<\/b>",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=111&docId=424222939&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=4&search_sort=0&spq=0",
			"description":"... 아님 미래를 위해 <b>빅데이터분석기사<\/b>로 가는게 나을까요  제가 정보처리산업기사를 취득후 1년 관련 업무를 했었습니다. 그래서 둘중에 하나를 따려고 하는데 정처산기 공부한게 있으니 정처기가 더 쉬울까요? 아님 미래를 위해... "
		},
		{
			"title":"<b>빅데이터 분석기사<\/b>",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=4&dirId=40608&docId=424167353&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=5&search_sort=0&spq=0",
			"description":"... 이상)이면 재학증명서를 제출하면 시험을 칠 수 있다고 하던데 10월에 치는 시험을 칠 수 있나요? 현재 113학점을 들었습니다. 해당 대학교에 학년이 4학년으로 등록되는 시점부터 <b>빅데이터분석기사<\/b> 시험에 응시할 수 있습니다 :D "
		},
		{
			"title":"<b>빅데이터 분석기사<\/b> 관련 질문 드립니다.",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=4&dirId=40608&docId=414251990&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=6&search_sort=0&spq=0",
			"description":"안녕하세요 하반기 <b>빅데이터 분석 기사<\/b> 취득을 목표를 하고 있습니다. <b>빅데이터 분석 기사<\/b> 관련 학원이나 인강이 있으면 추천 부탁 드립니다. <b>빅데이터 분석 기사<\/b> 자격증 취득을 희망하시는군요! IT 전문 학원에서 준비하시는게 좋으실것... "
		},
		{
			"title":"<b>빅데이터 분석기사<\/b> 응시자격",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=11004&docId=409552220&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=7&search_sort=0&spq=0",
			"description":"... 그럼 저도 <b>빅데이터 분석기사<\/b> 자격증 응시할 수 있는 건가요?? 안녕하세요~ 질문자님! 네 <b>빅데이터 분석기사<\/b>는 전공 상관없이 3년제 졸업이시면 경력 1년으로 응시조건 맞추실 수 있습니다. 산업기사, 기사 자격증같은... "
		},
		{
			"title":"<b>빅데이터 분석기사<\/b> 자격증",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=11&dirId=110503&docId=404755645&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=8&search_sort=0&spq=0",
			"description":"... <b>빅데이터분석기사<\/b> 응시자격에 대해 설명드리겠습니다 1. 학점은행제로 106학점 이상 보유자 (빠르면 6~8개월이면 가능) 2. 동일분야 자격으로 기사 이상 3. 2년제 관련학과 졸업자 + 실무경력 2년 이상 4. 3년제 관련학과 졸업자... "
		},
		{
			"title":"<b>빅데이터분석기사<\/b> 어떻게 공부해요?",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=11&dirId=110704&docId=419799457&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=9&search_sort=0&spq=0",
			"description":"안녕하세요 취업을 준비하고 있는 중인데 <b>빅데이터분석기사<\/b> 자격증이 있으면 취업하는데 좀 더 유리한 것 같아서 한번 <b>빅데이터분석기사<\/b> 시험에 응시해보려고 해요. <b>빅데이터분석기사<\/b> 시험 공부는 처음인지라 어려운 부분들이 있을 것... "
		},
		{
			"title":"<b>빅데이터 분석 기사<\/b>",
			"link":"https:\/\/kin.naver.com\/qna\/detail.naver?d1id=1&dirId=111&docId=409386027&qb=67mF642w7J207YSwIOu2hOyEneq4sOyCrA==&enc=utf8&section=kin.qna&rank=10&search_sort=0&spq=0",
			"description":"... # <b>빅데이터 분석기사<\/b> 응시자격을 대학학력 조건으로 맞추실때 기준이 있습니다. 1. 필기시험을 기준으로 최종학년에 재학중인 자 2. 전문대2\/3년제인 경우 직장 경력이 있어야 합니다. 위와 같은 조건에 맞지 않으신다면 당연히... "
		}
	]
}

,lastBuildDate,total,start,display,items
0,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터 분석기사</b>', 'link': 'https:/..."
1,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터 분석기사</b> 전공관련', 'link': 'ht..."
2,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터분석기사</b> 해볼까요?', 'link': 'ht..."
3,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '정보처리기사 vs <b>빅데이터분석기사</b>', 'link':..."
4,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터 분석기사</b>', 'link': 'https:/..."
5,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터 분석기사</b> 관련 질문 드립니다.', 'lin..."
6,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터 분석기사</b> 응시자격', 'link': 'ht..."
7,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터 분석기사</b> 자격증', 'link': 'htt..."
8,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터분석기사</b> 어떻게 공부해요?', 'link':..."
9,"Fri, 29 Jul 2022 09:23:22 +0900",15236,1,10,"{'title': '<b>빅데이터 분석 기사</b>', 'link': 'https:..."

- 과제 07/28 (3)

아래사항에 유의하여 OpenWeatherMap 날씨정보를 웹 API로 가져와서 출력하세요
* https://openweathermap.org/api 사이트에서 Current Weather data에 대한 API doc 내용을 파악
* 개발자 등록을 하고 API 키 발급 받음(https://home.openweathermap.org/users/sign_up)
* New Account 등록 후 API Keys라는 탭에서 API Key 확인 가능
* 기본적으로 유료 사이트이지만 현재 날씨, 5일까지의 날씨는 무료로 사용할 수 있음(단 1분에 60번만 호출 가능)
* 서울, 토쿄, 뉴욕의 날씨를 가져오는 프로그램 작성(text로 가져와서 json으로 변환하여 일차 출력)
  - cities = ["Seoul,KR", "Tokyo,JP", "New York,US"]
  - 가져올 정보 : 도시별 날씨(description), 최저 기온(temp_min), 최고 기온(temp_max), 습도(humidity), 기압(pressure), 풍속(speed)
  - 기온 데이터는 켈빈 온도로 되어 있으며 섭씨 온도로 변환해서 출력
* json 포멧으로 출력 데이터를 아래와 같이 가독력 있게 출력(소수점 2번째에서 반올림 처리)

https://openweathermap.org/api

In [ ]:
'''
+ 도시 = Seoul
| 날씨 = broken clouds
| 최저 기온 = -1.0 2
| 최고 기온 = 2.0 2
| 습도 = 74
| 기압 = 1023
| 풍속 = 0.5
'''

## 공공데이터 api

In [69]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
import pandas as pd
import json
import warnings
warnings.filterwarnings('ignore')

skey = 'uGamiWlbz5vqbmJXOUBORkCToFu5YdGGNHXDnA8tcyfdnldCmSBn3o%2F7PyA06mG1wUlUyiFlxEyRQkckNJ7qoQ%3D%3D'
res_id = 'storezone'
stype = 'json'    # type은 예약어니깐 쓰면안됨

url = 'http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi'
params = f'?ServiceKey={skey}&type={stype}&resId={res_id}&'+ urlencode({quote_plus('key'):'9174'})
query = url + params
print(query)

request = Request(query)
# response = requests.get(url, params=params)
# print(response.content)
request.get_method = lambda : 'GET'
response_body = urlopen(request).read()
# print(response_body)

response_dict = json.loads(response_body.decode('utf-8'))
items = response_dict['body']['items']

df = pd.DataFrame(items)
df

http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi?ServiceKey=uGamiWlbz5vqbmJXOUBORkCToFu5YdGGNHXDnA8tcyfdnldCmSBn3o%2F7PyA06mG1wUlUyiFlxEyRQkckNJ7qoQ%3D%3D&type=json&resId=storezone&key=9174

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9174,인사동,11,서울특별시,11110,종로구,226875,21,MULTIPOLYGON (((126.986059148338 37.5765234907...,2021-06-30

In [15]:
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
import pandas as pd
import json

def baro_api(skey,res_id,encode):
    
    stype = 'json'
    url = 'http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi'
    params = f'?ServiceKey={skey}&type={stype}&resId={res_id}&{encode}'
    query = url + params
    
    request = Request(query)
    request.get_method = lambda:'GET'
    response_body = urlopen(request).read()
    
    response_dict = json.loads(response_body.decode('utf-8'))
    items = response_dict['body']['items']
    df = pd.DataFrame(items)
    return df

##  상권조회

####  지정 상권조회

In [16]:
skey = 'uGamiWlbz5vqbmJXOUBORkCToFu5YdGGNHXDnA8tcyfdnldCmSBn3o%2F7PyA06mG1wUlUyiFlxEyRQkckNJ7qoQ%3D%3D'
res_id = 'storezone'
encode = urlencode({quote_plus('key'):'9193'})

baro_api(skey, res_id, encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9193,동대문역사문화공원역,11,서울특별시,11140,중구,79167,17,MULTIPOLYGON (((127.00304244009 37.56673071604...,2021-06-30

####  반경내 상권조회

In [17]:
# http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi?resId=storezone&catId=radius&radius=500&cx=127.004528&cy=37.567538&ServiceKey=서비스인증키

encode = urlencode({quote_plus('catId'):'radius',quote_plus('radius'):'500',
                   quote_plus('cx'):'127.004528',quote_plus('cy'):'37.567538'})

baro_api(skey, res_id, encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9170,동대문시장_1,11,서울특별시,11110,종로구,75046,13,MULTIPOLYGON (((127.00616674831 37.57097429301...,2021-06-30
1,9180,종로5가역_1,11,서울특별시,11110,종로구,44881,9,MULTIPOLYGON (((127.001579474423 37.5708212220...,2021-06-30
2,9192,동대문시장_2,11,서울특별시,11140,중구,60995,18,MULTIPOLYGON (((127.006693001676 37.5694470928...,2021-06-30
3,9193,동대문역사문화공원역,11,서울특별시,11140,중구,79167,17,MULTIPOLYGON (((127.00304244009 37.56673071604...,2021-06-30
4,9206,을지로4가역,11,서울특별시,11140,중구,81565,9,MULTIPOLYGON (((126.998050690253 37.5686092455...,2021-06-30

In [18]:
encode = urlencode({quote_plus('catId'):'radius', quote_plus('radius'):'500',
                   quote_plus('cx'):'127.004528', quote_plus('cy'):'37.567538'})

baro_api(skey,res_id,encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9170,동대문시장_1,11,서울특별시,11110,종로구,75046,13,MULTIPOLYGON (((127.00616674831 37.57097429301...,2021-06-30
1,9180,종로5가역_1,11,서울특별시,11110,종로구,44881,9,MULTIPOLYGON (((127.001579474423 37.5708212220...,2021-06-30
2,9192,동대문시장_2,11,서울특별시,11140,중구,60995,18,MULTIPOLYGON (((127.006693001676 37.5694470928...,2021-06-30
3,9193,동대문역사문화공원역,11,서울특별시,11140,중구,79167,17,MULTIPOLYGON (((127.00304244009 37.56673071604...,2021-06-30
4,9206,을지로4가역,11,서울특별시,11140,중구,81565,9,MULTIPOLYGON (((126.998050690253 37.5686092455...,2021-06-30

- 과제 07/28 (4)

####  사각형내 상권조회

In [19]:
# http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi?resId=storezone
#     &catId=rectangle&minx=126.978020&miny=37.557825&maxx=126.987732&
#     maxy=37.562022&ServiceKey=서비스인증키
from urllib.request import Request, urlopen
from urllib.parse import urlencode, quote_plus
import pandas as pd
import json

encode = urlencode({quote_plus('catId'):'rectangle', quote_plus('minx'):'126.978020',
                   quote_plus('miny'):'37.557825', quote_plus('maxx'):'126.987732',
                   quote_plus('maxy'):'37.562022',})

baro_api(skey,res_id,encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9191,남대문시장,11,서울특별시,11140,중구,111020,27,MULTIPOLYGON (((126.976451547074 37.5576325944...,2021-06-30
1,9196,명동역,11,서울특별시,11140,중구,96649,28,MULTIPOLYGON (((126.983476244148 37.5605598377...,2021-06-30

#### 행정단위 상권조회

In [20]:
# http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi?resId=storezone
#     &catId=dong&divId=adongCd&key=1168069000&ServiceKey=서비스인증키


encode = urlencode({quote_plus('catId'):'dong', quote_plus('divId'):'adongCd',
                   quote_plus('key'):'1168069000'})

baro_api(skey,res_id,encode)

,trarNo,mainTrarNm,ctprvnCd,ctprvnNm,signguCd,signguNm,trarArea,coordNum,coords,stdrDt
0,9324,포이사거리,11,서울특별시,11680,강남구,14033,33,MULTIPOLYGON (((127.044811833677 37.4781705036...,2021-06-30

##  상가업소 조회

#### 행정동 단위 상가업소 조회

In [21]:
# http://apis.data.go.kr/B553077/api/open/sdsc2/baroApi?resId=store&catId=dong&divId=ctprvnCd&key=11&ServiceKey=서비스인증키

res_id = 'store'
encode = urlencode({quote_plus('catId'):'dong',quote_plus('divId'):'ctprvnCd',quote_plus('key'):'11'})


baro_api(skey, res_id, encode)

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10001387,이음스튜디오,,D,소매,D18,사진/광학/정밀기기소매,D18A03,카메라판매,G47823,...,1168010700105910014011130,신사동빌딩,서울특별시 강남구 논현로154길 5,135893,06025,,1,,127.028616,37.521818
1,10004623,이철헤어커커,상계역점,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1135010600101410007000001,,서울특별시 노원구 한글비석로20길 43,139220,01662,,2,,127.074146,37.661098
2,10016187,일조산업,,D,소매,D07,가정/주방/인테리어,D07A15,유리/페인트/철물건축자재,G47519,...,1120011500102800040003693,일조산업,서울특별시 성동구 광나루로 290,133120,04796,,,,127.061970,37.547705
3,10030788,장안순대국밥,,Q,음식,Q10,별식/퓨전요리,Q10A05,순대전문점,I56111,...,1123010500105300016018329,,서울특별시 동대문구 고미술로 81,130032,02622,,1,,127.055701,37.565595
4,10031349,장어야,동자동점,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1117010700100350141024265,,서울특별시 용산구 후암로57길 51-3,140821,04324,,,,126.974149,37.551236
5,10031436,장어천국,,Q,음식,Q01,한식,Q01A01,한식/백반/한정식,I56111,...,1165010400103720003004086,,서울특별시 서초구 원터4길 3,137150,06806,,2,,127.055836,37.443503
6,10034303,재건공조,,D,소매,D07,가정/주방/인테리어,D07A15,유리/페인트/철물건축자재,G47519,...,1123010300111490017032382,,서울특별시 동대문구 종암로 6,130865,02465,,1,,127.036595,37.590976
7,10034977,재진패션,,D,소매,D05,의복의류,D05A01,일반의류,G47416,...,1162010200114800001003292,계림빌딩,서울특별시 관악구 난곡로57길 11,151894,08771,,2,,126.914212,37.479482
8,10038561,전자랜드프라이스킹,은평점,D,소매,D12,가전제품소매,D12A01,일반가전제품,G47320,...,1138010700101090006000001,,서울특별시 은평구 은평로 122,122010,03454,,1,,126.921329,37.600043
9,10041487,정관장,서대문역점,D,소매,D03,종합소매점,D03B04,시장/종합상가,G47129,...,1141010400101670000029786,로얄빌딩,서울특별시 서대문구 통일로 111,120020,03738,,1,,126.967217,37.564800
10,10041503,정관장,남부법원점,D,소매,D10,건강/미용식품,D10A04,건강식품판매,G47216,...,1147010100110130004003329,성배법조빌딩,서울특별시 양천구 신월로 369,158070,08021,,,,126.861992,37.522403
11,10050747,제시카키친,이대하늬솔점,Q,음식,Q06,양식,Q06A05,패밀리레스토랑,I56114,...,1141011300100850001030936,하늬솔빌딩,서울특별시 서대문구 성산로 527,120160,03721,A,1,,126.944072,37.563766
12,10056742,제일전기조명,,D,소매,D07,가정/주방/인테리어,D07A10,조명기구/전기용품,G47591,...,1111015700100800001014076,,서울특별시 종로구 창경궁로 127,110410,03136,,1,,126.997296,37.573790
13,10065677,종가집설렁탕,,Q,음식,Q01,한식,Q01A09,설렁탕집,I56111,...,1147010100102960077006237,,서울특별시 양천구 신목로 56,158070,08015,,,,126.872936,37.519849
14,10072281,주연테크컴퓨터,신촌점,D,소매,D08,사무/문구/컴퓨터,D08A05,컴퓨터전문매장,G47311,...,1141011000101560034026971,,서울특별시 서대문구 신촌로 249,120821,03774,,,,126.953668,37.557472
15,10075124,준오헤어돈암2호점,돈암2호점,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1129011600100850104000001,,서울특별시 성북구 동소문로22길 39,136051,02845,,2,,127.018438,37.591403
16,10080606,중화공인중개사사무소,,L,부동산,L01,부동산중개,L01A01,부동산중개,L68221,...,1126010300101100018013614,,서울특별시 중랑구 봉화산로 76,131120,02089,,1,,127.082755,37.601606
17,10085207,GS25,용산하얏트점,D,소매,D03,종합소매점,D03A01,편의점,G47122,...,1117013000102430037009047,,서울특별시 용산구 회나무로44길 46,140200,04346,,1,,126.995255,37.539470
18,10086312,지우미용실신월점,신월점,F,생활서비스,F01,이/미용/건강,F01A01,여성미용실,S96112,...,1147010300104430005010798,,서울특별시 양천구 오목로 41,158090,07930,,1,,126.842187,37.522183
19,10088738,지혜수산,화곡역점,Q,음식,Q03,일식/수산물,Q03A02,음식점-일식,I56113,...,1150010300110680023029683,동인빌딩,서울특별시 강서구 화곡로 119,157010,07711,,,,126.835093,37.540431